/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.View;

import mvc.Model.Conexion;

/**
 *
 * @author Correa
 */
public class ActualizarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarUsuario
     */
    public ActualizarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchName = new javax.swing.JFormattedTextField();
        SearchEmail = new javax.swing.JFormattedTextField();
        jButton7 = new javax.swing.JButton();
        SearchId = new javax.swing.JFormattedTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(14, 20, 27));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        SearchName.setBackground(new java.awt.Color(255, 255, 255));
        SearchName.setBorder(null);
        SearchName.setForeground(new java.awt.Color(0, 0, 0));
        SearchName.setText(" Nuevo nombre");
        SearchName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SearchName.setMargin(new java.awt.Insets(10, 6, 2, 6));
        SearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchNameActionPerformed(evt);
            }
        });
        jPanel2.add(SearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 260, 30));

        SearchEmail.setBackground(new java.awt.Color(255, 255, 255));
        SearchEmail.setBorder(null);
        SearchEmail.setForeground(new java.awt.Color(0, 0, 0));
        SearchEmail.setText(" Nuevo email");
        SearchEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SearchEmail.setMargin(new java.awt.Insets(10, 6, 2, 6));
        SearchEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmailActionPerformed(evt);
            }
        });
        jPanel2.add(SearchEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 260, 30));

        jButton7.setBackground(new java.awt.Color(96, 195, 250));
        jButton7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Actualizar Usuario");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 200, 47));

        SearchId.setBackground(new java.awt.Color(255, 255, 255));
        SearchId.setBorder(null);
        SearchId.setForeground(new java.awt.Color(0, 0, 0));
        SearchId.setText(" Buscar id");
        SearchId.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SearchId.setMargin(new java.awt.Insets(10, 6, 2, 6));
        SearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIdActionPerformed(evt);
            }
        });
        jPanel2.add(SearchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 260, 30));

        jButton9.setBackground(new java.awt.Color(96, 195, 250));
        jButton9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Salir");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 200, 47));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -1, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchEmailActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Conexion conexion = new Conexion();
        
        conexion.actualizarUsuario(Integer.parseInt(SearchId.getText()), SearchName.getText(), SearchEmail.getText());       
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void SearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchIdActionPerformed

    private void SearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchNameActionPerformed

    private void jButton9jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton9jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField SearchEmail;
    private javax.swing.JFormattedTextField SearchId;
    private javax.swing.JFormattedTextField SearchName;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
